// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"faizalmaulana/lsp/models/repo"
	"github.com/gin-gonic/gin"
	"net/http"
)

// Injectors from wire.go:

func InitializeApp() *App {
	config := ProvideEnvConfig()
	db := ProvideDB(config)
	usersRepo := ProvideUsersRepo(db)
	authenticationService := ProvideAuthenticationService(usersRepo)
	sessionsRepo := ProvideSessionsRepo(db)
	sessionService := ProvideSessionService(sessionsRepo)
	authenticationHandler := ProvideAuthenticationHandler(authenticationService, sessionService, config)
	profilesRepo := ProvideProfilesRepo(db)
	profilesService := ProvideProfilesService(profilesRepo)
	usersService := ProvideUsersService(usersRepo)
	usersHandler := ProvideUsersHandler(config, profilesService, usersService)
	itemsRepo := ProvideItemsRepo(db)
	itemsService := ProvideItemsService(itemsRepo)
	transactionsRepo := ProvideTransactionsRepo(db)
	transactionsService := ProvideTransactionsService(transactionsRepo)
	pivotItemsToTransactionsRepo := ProvidePivotItemsToTransactionsRepo(db)
	transactionsHandler := ProvideTransactionsHandler(config, transactionsService, itemsRepo, pivotItemsToTransactionsRepo)
	reportHandler := ProvideReportHandler(config, transactionsService, pivotItemsToTransactionsRepo, itemsRepo)
	imagesRepo := ProvideImagesRepo(db)
	imagesService := ProvideImagesService(imagesRepo)
	imagesHandler := ProvideImagesHandler(config, imagesService)
	itemsHandler := ProvideItemsHandler(config, itemsService, imagesService)
	engine := ProvideRouterWithRoutes(authenticationHandler, usersHandler, itemsHandler, transactionsHandler, reportHandler, imagesHandler)
	server := ProvideHTTPServer(config, engine)
	app := &App{
		Server: server,
		Router: engine,
	}
	return app
}

func InitializeRepos() *Repos {
	config := ProvideEnvConfig()
	db := ProvideDB(config)
	usersRepo := ProvideUsersRepo(db)
	profilesRepo := ProvideProfilesRepo(db)
	repos := &Repos{
		Users:    usersRepo,
		Profiles: profilesRepo,
	}
	return repos
}

// wire.go:

type App struct {
	Server *http.Server
	Router *gin.Engine
}

type Repos struct {
	Users    repo.UsersRepo
	Profiles repo.ProfilesRepo
}

func InitializeServer() *http.Server {
	app := InitializeApp()
	return app.Server
}
